<?php echo $this->doctype();?>
<html>
<head>
	<?php echo $this->headLink();?>
	<?php echo $this->headMeta();?>
	<?php echo $this->headTitle();?>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
</head>
<body>
	<div>
		<?php echo $this->partial('header.phtml');?>
		<div>
			<?php echo $this->layout()->content;?>
		</div>
	</div>
	<div>
		<?php echo $this->partial('footer.phtml');?>
	</div>

</body>
</html>